### ISSUE TITLE
Remake of the PCB

### ISSUE THREAD

**Issue by c3n3** [ksurct/mercury2021#10]
Things that need to be done with the PCB:

1. 3.3 V Rail
2. Fix Power circuit
3. Make Sensor connectors able to be directly ribbon cabled

Fancy stuff:
1. Make connection directly to raspberry pi.
- PI -> motor drivers, servo multiplextor
2. Connect motor drivers to board
3. Connect servo multiplexor

**Comment by MaxMyzer** [comment]
How do you recommend I make a 3.3v rail? Arduino and Pi, or another regulator?

**Comment by c3n3** [comment]
@MaxMyzer Just stick it on the arduino. It will be used as encoder power inputs, which will be read on the arduino

**Comment by MaxMyzer** [comment]
Oh, lol I had just added it with another regulator of the same family as the 5v one. Should I use the Arduino instead then?

**Comment by MaxMyzer** [comment]
How big big a 3.3v rail we talking? Same size as the others?

**Comment by MaxMyzer** [comment]
wow finding ribbon cables is hard

**Comment by MaxMyzer** [comment]
Before we order the PCB I would like to 3d print the 3d model of it so we can test fit things

**Comment by c3n3** [comment]
@MaxMyzer certainly doable, we can export it as an stl, will be easy. Ya, there are some ribbon cables we can cut down to the correct size. We can review all this tomorrow. The 3.3V rail I would make a bit generous, probably like 8 pins or so...

**Comment by MaxMyzer** [comment]
TODO: 

- [ ] Add LED indicator
- [ ] Add silkscreen of team
- [ ] Get correct footprints for: USB Connector
- [ ] Get correct footprints for: Screw Terminal
- [ ] Get correct footprints for: Ribbon Cables
- [ ] Get correct footprints for: JST connector (Motor Driver)
- [ ] 3D print the board to test the connectors and spacing before getting it made.
